# Generated by Django 4.2.16 on 2024-10-01 20:30

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
      #   ('quiz', '000X_previous_migration'),  # Replace with the last migration number
       #  ('course', '000X_previous_migration'),  # Replace with the last migration number for the course app
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subcourse'),
        ),
    ]
